services:
  - type: static
    name: stocklens
    buildCommand: npm ci --legacy-peer-deps && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
